baseURL: "https://blog.engineernathan.org/"
title: "Nathan's Engineering Blog"
description: "Nathan's tech and engineering blog"
author: "Nathan Boyd"
paginate: 50
theme: PaperMod
languageCode:  "en-us"
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
enableGitInfo: true
keywords: [Tech, Software, Engineering, Blog]
pygmentsCodefences: true
pygmentsCodefencesGuessSyntax: true
pygmentsStyle: "monokai"
googleAnalytics: G-FFN3MQXMGK
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
minify:
    disableXML: true
    minifyOutput: true
menu:
    main:
        - name: Posts
          url: posts
          weight: 5
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10
        - name: Archive
          url: archives/
          weight: 5
        - name: Search
          url: search/
          weight: 5
params:
    env: production
    ShowToc: true
    defaultTheme: auto
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: false
    comments: false
    images: ["papermod-cover.png"]
    homeInfoParams:
        Title: "hi there \U0001F44B"
        Content: Well this is interesting, you've found my software and tech blog! Welcome and feel free to reach out to me on one of the socials below.
    socialIcons:
        - name: "kofi"
          url: "https://ko-fi.com/nathanboyd"
        - name: twitter
          url: "https://twitter.com/nathanboyd/"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/551922/nathan-boyd/"
        - name: github
          url: "https://github.com/nathan-boyd/"
        - name: rss
          url: "index.xml"
        - name: linkedin
          url: "https://www.linkedin.com/in/boydnathan/"
    editPost:
        URL: "https://github.com/nathan-boyd/engineering_blog/tree/main/content/"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link
    assets:
        favicon: img/favicon.png
        favicon16x16: img/favicon-16x16.png
        favicon32x32: img/favicon-32x32.png
        apple_touch_icon: img/apple-touch-icon.png
        safari_pinned_tab: img/favicon.ico
taxonomies:
    category: categories
    tag: tags
    series: series
markup:
    goldmark:
        renderer:
            unsafe: true
privacy:
    vimeo:
        disabled: false
        simple: true
    twitter:
        disabled: false
        enableDNT: true
        simple: true
    instagram:
        disabled: false
        simple: true
    youtube:
        disabled: false
        privacyEnhanced: true
services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
deployment:
    targets:
        name: "s3"
        URL: "s3://blog.engineernathan.org?region=us-east-1"
